name: Lint & Format
on:
  push:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs (if any)
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          github_token: ${{ github.token }}
          ref: ${{ github.HEAD_REF }}
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.9.x"
          architecture: "x64"
      - name: Build
        run: |
          pip install --upgrade pip setuptools wheel
          pip install pipenv
          make build
      - name: Format
        run: make format
      - name: Lint
        run: make lint
      - name: Typecheck
        run: make typecheck
